server:
   port: 3344
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liufei4552/microservicecloud-config.git #github上面的git仓库







